name: Docker

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker Metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: quay.io/rtctunnel/rtctunnel

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: rtctunnel+github
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
